
ALTER TABLE public.companies 
ADD COLUMN IF NOT EXISTS trade_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS cnae_principal TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS cnae_secundario TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS activity_risk TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS cep TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS neighborhood TEXT NOT NULL DEFAULT '';
