// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockSupabase } from '@/lib/mock-db';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";

// Chaves oficiais Spartan
const ACCESS_SECRET = "SPARTAN-2024-MGCONSULT";
const DEV_SECRET = "SPARTAN-DEV-DIOGO-2024";

const checkAccess = () => {
  // Verificar no LocalStorage (licença persistente inserida via UI)
  const storedLicense = localStorage.getItem("spartan_license_key");
  
  if (storedLicense === ACCESS_SECRET || storedLicense === DEV_SECRET) {
    return true;
  }
  
  // Verificar no SessionStorage (opcional)
  const storedSession = sessionStorage.getItem("spartan_access_token");
  return storedSession === ACCESS_SECRET || storedSession === DEV_SECRET;
};

export const isRealDb = checkAccess();

export const supabase = isRealDb 
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : mockSupabase as any;